version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mongo

  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"

  db-ui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://db:27017/
